Mlx wrapper
tozeki722105/ft_cub3D pull request #21
Opened 2024-08-19 07:44 UTC by taka-chin

mlx_wrapperの実装と残っていたnormの対応を実施しました
確認お願いします！

2024-08-19 12:55 UTC, tozeki722105 requested changes

2024-08-19 12:55 UTC, tozeki722105 commented on srcs/main.c
> +	mlx->map.data = ft_double_str_dup(loader.map_data);
ft_x_double_str_dupにしゅうせいしてして

2024-08-20 00:02 UTC, taka-chin commented on srcs/main.c
> +	mlx->map.data = ft_double_str_dup(loader.map_data);
修正したのでmergeしてください

2024-08-20 06:31 UTC, tozeki722105 commented
確認しました！ありがとうございます！

2024-08-20 06:31 UTC, merged